version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: mythologizer_postgres_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_test:/var/lib/postgresql/data_test
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata_test:
